### PR TITLE
Line endings

### PR DESCRIPTION
**Pull request by mfp22**
This file had a mixture of LF and CRLF line endings. This makes it consistent so it's not so intimidating for people to contribute to obsidian.d.ts in the future. 

This PR adds a file that hopefully fixes this for everyone contributing to this repo. 

Looks like this was recognized as an issue [before](https://github.com/obsidianmd/obsidian-api/pull/113)

But the inconsistent line endings were added [later](https://github.com/obsidianmd/obsidian-api/commit/d6f80eccf6a6f0d1ec314605bdb7e9489311503f)

### CODE REVIEW

**Comment by lishid** [comment]
I have reformatted the file with uniform line endings.

**Comment by mfp22** [comment]
So you would rather do that work yourself than simply merge my PR that has that fix _AND_ a permanent fix to the problem? Do you need this issue to keep recurring for your GitHub contributions chart, or do you have a policy of never merging PRs from new people?

**Comment by lishid** [comment]
The definition file is automatically generated - your PR simply fix the file as it is, but it will get overwritten by the next run of the generator.

**Comment by lishid** [comment]
I want to note that I am not against PRs in general, nor anything against you or new contributors. Given the nature of the build system (it's unfortunately quite finnicky with formatting) it is impractical to manually edit the output file.

**Comment by mfp22** [comment]
The fact that inconsistent line endings were ever introduced means that my 2nd file, which wouldn't be overridden if only the definitions file is regenerated, would have been useful, at least in the past. Either this repo is totally closed to new PRs, or that file would have been useful. 

Why don't you mention in the README that this whole repo is closed to PRs? I wouldn't have just spent an hour on these 2 PRs.

**Comment by lishid** [comment]
Apologies this was an oversight - I have added a note here: https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L2

**Pull request closed without merging**
