### PR TITLE
Add a deprecation notice for registerCodeMirror().

### PR DESCRIPTION
**Pull request by Taitava**
Most part of the comment is copied from NothingIsLost's comment on Discord: https://discord.com/channels/686053708261228577/840286264964022302/922498798125731880

### CODE REVIEW

**Comment by kometenstaub** [comment]
It looks like you reformatted a lot of the document, instead of just adding the changes.

**Comment by Taitava** [comment]
Damn, I hate it when IDEs do automatic formatting without even showing the changes they made when committing to git. 🙁

I'll fix it in a while.

**Comment by Taitava** [comment]
Fixed line endings.

**Comment by lishid** [comment]
I've added a different message for the deprecation, thank you!

**Pull request closed without merging**
