### PR TITLE
Add getBacklinksToFile

### PR DESCRIPTION
**Pull request by mfp22**
If you merge [this PR](https://github.com/obsidianmd/obsidian-api/pull/115) first, you'll see the diff for just this PR.

This PR just adds typing for `getBacklinksToFile`.

### CODE REVIEW

**Comment by lishid** [comment]
Private APIs are not documented because they are private. There are loads of methods and fields that exists at runtime but isn't in the API because we have not committed to supporting them through the API.

If you decide to use a private API you can do so by adding it in your own local `.d.ts` file in your plugin repo.

**Comment by mfp22** [comment]
I would rather be broken by a change in TypeScript than a runtime JavaScript error. If I define my own types, they are lies. You should allow developers to contribute to types that describe current reality, but with the @experimental tag. I guess I know now why there are 162 forks and only 15 PRs.

**Comment by lishid** [comment]
I understand your perspective, but any definition identified here will get used without regard - and subsequently complained about if they were changed. Also, `obsidian.d.ts` is just a type definition, so it works exactly the same way as if you defined your own types.

**Comment by felixqueisler** [comment]
I'd also need this in the API. API seems incomplete and inconsequential without it.

**Comment by chriselderxyz** [comment]
Man I wish this got merged, getting links for a file seems like a necessity for an app focused on linking notes lol

**Comment by mnaoumov** [comment]
This won't get merged as it's an internal API the team doesn't want to expose

**Pull request closed without merging**
